Fixes for the following issues: PRODUCTION RUN It ran for about 10 hours. After about 4 hours, this happened: 2025-10-10 00:13:18,765 - file_organizer - ERROR - Failed to commit changes in /Users/me/Google Drive/My Drive/MyFiles/dev: Command '['git', 'add', '-A']' returned non-zero exit status 128. 2025-10-10 00:13:18,765 - file_organizer - INFO - Syncing (2/6): /Users/me/pol -> /Users/me/ProtonDrive/pol 2025-10-10 00:13:20,036 - file_organizer - INFO - Using rsync (checksum mode) to sync /Users/me/pol -> /Users/me/ProtonDrive/pol 2025-10-10 00:13:20,036 - file_organizer - INFO - Running rsync with checksum comparison
Then it recovered, and this happened:
2025-10-10 06:20:05,960 - file_organizer - ERROR - rsync failed: rsync(91974): error: 2025/.abc.5buOPcYR82: move_file: 2025/abc.pages: Input/output error

If an external drive isn't plugged in, it should handle it gracefully, instead of

2025-10-10 06:20:05,962 - file_organizer - INFO - Syncing (3/6): /Users/me/xyx -> /Volumes/EXTERNAL_DRIVE/xyz
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/pathlib/_local.py", line 722, in mkdir
    os.mkdir(self, mode)
    ~~~~~~~~^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/EXTERNAL_DRIVE/xyz'

During handling of the above exception, another exception occurred:

PermissionError: [Errno 13] Permission denied: '/Volumes/EXTERNAL_DRIVE'

A further problem is, there are far too many soft link directories in /Users/me/organized:

ls -l organized/ | wc -l
77
ls organized/
drwxr-xr-x    14    448 Oct  9 23:57 documents
drwxr-xr-x   540  17280 Oct 10 00:07 eae
...
drwxr-xr-x   200   6400 Oct 10 00:07 yee

There are about 70 of these three-letter soft folders

ls -l organized/eae |wc -l
538

ls organized/eae
vienna-camping-neue-donat-schnitzels.jpg
...